name = "whatsapp"
main = "cloudflare/worker.js"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./frontend"
binding = "ASSETS"

[vars]
ALWAYSDATA_BASE_URL = "https://goharrehman.alwaysdata.net"
